<?php
/**
 * Plugin Name: Larkspur — the demonstration itself
 * Description: What makes this WordPress install a Busymate AI demo rather than
 *              just a business site: an inline chat surface (shortcode + block)
 *              alongside the floating widget, the page's own WebMCP tools, the
 *              one-click sign-in that provides the demo customer, and a small
 *              fallback rule for a WordPress core CSS gap this host hit.
 * Version:     1.0.0
 * Author:      Busymate AI demo playground
 *
 * WHY THIS IS AN MU-PLUGIN AND NOT PART OF `busymate-ai`. `busymate-ai` (in
 * `wp-content/plugins/`) is the REAL, generic per-tenant plugin generated by
 * this product's own `buildWordPressPlugin` (v2/apps/web/lib/commerce/
 * wordpressPlugin.ts, #2842) — the same generator that produced woo's copy.
 * Everything specific to THIS demo (its shortcode/block, its page tools, its
 * one throwaway customer) lives here instead, exactly the way woo's own
 * `fernweh-demo-experience.php` keeps the demo layer separate from the
 * generic plugin it sits on top of (busymate-devtools#2969, program #2899).
 *
 * @package Larkspur_Demo
 */

defined( 'ABSPATH' ) || exit;

const LARKSPUR_DEMO_CUSTOMER_EMAIL = 'jordan@wordpress.demo.busymate.ai';
const LARKSPUR_SIGNIN_PATH         = '/larkspur-demo-signin';
/**
 * The hosted-assistant origins the sign-in redirect may return a visitor to,
 * besides this site itself — same two-origin shape as woo's
 * `FERNWEH_HOSTED_ORIGINS` and for the same reason: a click from the platform's
 * OWN hosted chat page (`busymate.ai/support/larkspur`, or this workspace's
 * `larkspur.busymate.ai`) has to come back to whichever one it left from, or
 * the token never reaches the frame that asked for it.
 */
const LARKSPUR_HOSTED_ORIGINS = 'https://larkspur.busymate.ai,https://busymate.ai';

/*
 * ── The provided customer — the identity-provider LOGIN endpoint ───────────
 * Half two of the identity handoff (half one is the `busymate-ai` plugin's
 * own getIdentity, which only works once a visitor is ALREADY logged in).
 * This is the redirect the tenant identity provider's `login_url` points at:
 * it signs the visitor in as the ONE throwaway demo customer, mints the same
 * ES256 launch proof the plugin's own /wp-json/busymate/v1/launch route
 * mints, and hands it back in the URL FRAGMENT so it never touches a server
 * log. wp-login.php stays 404 to the public (nginx hardening) — this is the
 * only way in, and it can only ever sign in the one named account.
 *
 * @return void
 */
function bmai_demo_signin() {
	if ( is_admin() ) {
		return;
	}
	$uri  = isset( $_SERVER['REQUEST_URI'] ) ? wp_unslash( $_SERVER['REQUEST_URI'] ) : '';
	$path = is_string( $uri ) ? wp_parse_url( $uri, PHP_URL_PATH ) : '';
	if ( LARKSPUR_SIGNIN_PATH !== untrailingslashit( (string) $path ) ) {
		return;
	}

	$user = get_user_by( 'email', LARKSPUR_DEMO_CUSTOMER_EMAIL );
	if ( ! $user ) {
		status_header( 503 );
		header( 'Content-Type: application/json; charset=utf-8' );
		echo wp_json_encode( array( 'error' => 'demo_customer_missing' ) );
		exit;
	}

	wp_set_current_user( $user->ID );
	wp_set_auth_cookie( $user->ID, false, true );

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- a navigation entry point, not a state change beyond this demo session.
	$requested = isset( $_GET['return_to'] ) ? esc_url_raw( wp_unslash( $_GET['return_to'] ) ) : '';
	$target    = bmai_allowed_return_to( $requested );

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- this is the platform's one-time launch nonce, not a WordPress form nonce.
	$asked    = isset( $_GET['bmai_nonce'] ) ? sanitize_text_field( wp_unslash( $_GET['bmai_nonce'] ) ) : '';
	$nonce    = preg_match( '/^[A-Za-z0-9_-]{32,200}$/', $asked ) ? $asked : '';
	$fragment = bmai_launch_fragment( $user->ID, $nonce );
	if ( $fragment ) {
		$target .= ( false === strpos( $target, '#' ) ? '#' : '&' ) . $fragment;
	}

	header( 'Cache-Control: no-store' );
	header( 'Referrer-Policy: no-referrer' );
	wp_redirect( $target, 303 ); // phpcs:ignore WordPress.Security.SafeRedirect.wp_redirect_wp_redirect -- the target is already pinned to home_url below.
	exit;
}
add_action( 'init', 'bmai_demo_signin', 2 );

/**
 * The EXACT `return_to`, when its origin is this site or the platform;
 * the front page otherwise. Compared on the parsed ORIGIN, never a prefix.
 *
 * @param string $requested The raw `return_to` as it arrived.
 * @return string
 */
function bmai_allowed_return_to( $requested ) {
	$home = home_url( '/' );
	if ( ! $requested ) {
		return $home;
	}
	$parts = wp_parse_url( $requested );
	if ( ! is_array( $parts ) || empty( $parts['scheme'] ) || empty( $parts['host'] ) ) {
		return $home;
	}
	if ( 'https' !== strtolower( $parts['scheme'] ) || ! empty( $parts['user'] ) || ! empty( $parts['pass'] ) ) {
		return $home;
	}
	$origin  = 'https://' . strtolower( $parts['host'] ) . ( empty( $parts['port'] ) ? '' : ':' . $parts['port'] );
	$allowed = array_merge(
		array( untrailingslashit( home_url() ) ),
		explode( ',', LARKSPUR_HOSTED_ORIGINS )
	);
	return in_array( $origin, $allowed, true ) ? $requested : $home;
}

/**
 * The launch proof, signed by the same key and claim set the `busymate-ai`
 * plugin's own /launch route uses (`busymate_ai_launch_claims`, filtered
 * below to add the two DISPLAY claims a greeting/order-style flow reads).
 *
 * @param int    $user_id The signed-in user.
 * @param string $nonce   The nonce the caller asked to have echoed; '' mints one.
 * @return string The URL fragment, or '' when identity is unavailable.
 */
function bmai_launch_fragment( $user_id, $nonce = '' ) {
	if ( ! class_exists( 'Bmai_Keys' ) || ! defined( 'BMAI_TENANT_ID' ) ) {
		return '';
	}
	if ( ! $nonce ) {
		$nonce = rtrim( strtr( base64_encode( random_bytes( 24 ) ), '+/', '-_' ), '=' ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- base64url, not obfuscation.
	}
	$now    = time();
	$claims = array(
		'iss'             => class_exists( 'Bmai_Rest' ) ? Bmai_Rest::issuer() : untrailingslashit( home_url() ),
		'aud'             => BMAI_AUDIENCE,
		'sub'             => (string) $user_id,
		BMAI_TENANT_CLAIM => BMAI_TENANT_ID,
		'nonce'           => $nonce,
		'jti'             => wp_generate_uuid4(),
		'iat'             => $now,
		'exp'             => $now + BMAI_TOKEN_TTL,
	);
	$claims = apply_filters( 'busymate_ai_launch_claims', $claims, $user_id );
	$token  = Bmai_Keys::sign_jwt( $claims );
	if ( is_wp_error( $token ) || ! is_string( $token ) ) {
		return '';
	}
	return 'bmai_token=' . rawurlencode( $token ) . '&bmai_nonce=' . rawurlencode( $nonce );
}

/**
 * The display claims (name/email) — same rationale as woo's identical filter:
 * an email a visitor TYPES is unverified, but one the STORE signs for its own
 * signed-in user is a verified claim, and it is only ever this one invented
 * demo mailbox on this demo's own domain.
 *
 * @param array $claims  The claim set the plugin is about to sign.
 * @param int   $user_id The signed-in user.
 * @return array
 */
function bmai_launch_display_claims( $claims, $user_id ) {
	$user = get_userdata( $user_id );
	if ( ! $user ) {
		return $claims;
	}
	$claims['name']  = $user->display_name;
	$claims['email'] = $user->user_email;
	return $claims;
}
add_filter( 'busymate_ai_launch_claims', 'bmai_launch_display_claims', 10, 2 );

/**
 * `[bmai_assistant]` — an inline chat surface using the SAME `/support/<slug>`
 * frame the floating widget's own iframe points at (embed/v1.js), just
 * mounted in the page flow instead of a corner FAB. Also registered as a
 * Gutenberg block (`busymate-ai/assistant`) below, sharing this renderer.
 *
 * @return string
 */
function bmai_assistant_shortcode() {
	$src = sprintf(
		'%s/support/%s?channel=embed&bridge=busymate-ai-v1',
		untrailingslashit( BMAI_EMBED_ORIGIN ),
		rawurlencode( BMAI_TENANT_SLUG )
	);
	return sprintf(
		'<div class="bmai-inline-assistant" style="margin:2em auto;max-width:480px;border:1px solid #e2e2e2;border-radius:16px;overflow:hidden;box-shadow:0 8px 30px rgba(0,0,0,.08)">'
			. '<iframe src="%1$s" title="%2$s" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="tools; microphone; autoplay" sandbox="allow-scripts allow-forms allow-same-origin" style="display:block;width:100%%;height:640px;border:0;background:#111"></iframe>'
			. '</div>',
		esc_url( $src ),
		esc_attr__( 'AI assistant', 'busymate-ai' )
	);
}
add_shortcode( 'bmai_assistant', 'bmai_assistant_shortcode' );

/**
 * The same shortcode as a Gutenberg block — no build step: a dynamic,
 * server-rendered block registered straight from PHP (`render_callback`),
 * so an editor can insert "AI Assistant" from the block inserter instead of
 * typing the shortcode. Shows up in the block list under the "Widgets"
 * category with a chat-bubble icon.
 *
 * @return void
 */
function bmai_register_assistant_block() {
	register_block_type(
		'busymate-ai/assistant',
		array(
			'render_callback' => 'bmai_assistant_shortcode',
			'attributes'       => array(),
			'title'            => __( 'AI Assistant', 'busymate-ai' ),
			'category'         => 'widgets',
			'icon'             => 'format-chat',
			'description'      => __( 'Embeds the Busymate AI assistant inline on this page (the same assistant as the floating widget).', 'busymate-ai' ),
		)
	);
}
add_action( 'init', 'bmai_register_assistant_block' );

/**
 * A signed-in visitor's display name, exposed on <html> so the page-tools JS
 * (running in the visitor's own session) can read it without another
 * round-trip — the same shape woo's `data-fernweh-customer` uses.
 *
 * @param string $output The existing language-attributes string.
 * @return string
 */
function bmai_language_attributes( $output ) {
	if ( is_user_logged_in() ) {
		$user   = wp_get_current_user();
		$output .= sprintf( ' data-larkspur-customer="%s"', esc_attr( $user->display_name ) );
	}
	return $output;
}
add_filter( 'language_attributes', 'bmai_language_attributes' );

/**
 * WebMCP page tools for this content site (busymate-devtools#2969, program
 * §3.2/§3.5 — memory `webmcp-adopt-everywhere`): read-only service/contact
 * lookups plus one consequential action (`request_consultation`), which
 * calls this plugin's OWN REST route below — so the tool's logic has one
 * source of truth, same as the runbook's full-feature-demo standard.
 *
 * Printed on the front end only, deferred until `window.BusymateAI.
 * registerPageTools` exists (the embed script itself loads deferred).
 *
 * @return void
 */
function bmai_enqueue_page_tools() {
	if ( is_admin() ) {
		return;
	}
	wp_register_script( 'bmai-page-tools', false, array(), '1.0.0', true );
	wp_enqueue_script( 'bmai-page-tools' );
	wp_add_inline_script( 'bmai-page-tools', bmai_page_tools_js() );
}
add_action( 'wp_enqueue_scripts', 'bmai_enqueue_page_tools', 20 );

/**
 * Core's own `core/cover` block stylesheet (the position/object-fit rules
 * that make its background image fill the block instead of rendering as a
 * plain inline `<img>` behind the dim overlay) is not being enqueued on this
 * install — `wp-block-button`/`gallery`/`heading`/`image`/`paragraph`/
 * `columns` all load their per-block stylesheet on this theme, `cover` alone
 * does not (seen live on the hero: the photo loads at 200 but paints as a
 * flat grey box). Rather than chase why core's own enqueue skips exactly one
 * block on this host, print the same core rule the missing stylesheet would
 * have carried — small, scoped to the block's own classnames, and dropped
 * the moment the real stylesheet starts loading (an extra copy of the same
 * rule is harmless).
 *
 * @return void
 */
function bmai_cover_block_style_fallback() {
	if ( is_admin() ) {
		return;
	}
	echo '<style id="bmai-cover-fallback">'
		. '.wp-block-cover{position:relative;overflow:hidden;display:flex}'
		. '.wp-block-cover__image-background,.wp-block-cover__video-background{position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover}'
		. '.wp-block-cover__background{position:absolute;inset:0}'
		. '.wp-block-cover__inner-container{position:relative;width:100%;z-index:1;color:inherit;margin:auto 0}'
		. '</style>' . "\n";
}
add_action( 'wp_head', 'bmai_cover_block_style_fallback', 20 );

/**
 * The inline page-tools script body. ES5-safe, dependency-free — same
 * constraint as the identity bridge in the `busymate-ai` plugin.
 *
 * @return string
 */
function bmai_page_tools_js() {
	$consult_url = esc_url_raw( rest_url( 'busymate/v1/consultation' ) );
	$nonce       = wp_create_nonce( 'wp_rest' );
	return
		'(function () {' .
		'  var SERVICES = [' .
		'    { name: "Design Package", from: "£2,400", summary: "A full plan for a room, floor or whole home: survey, layout options, materials and lighting palette, buildable spec sheet. 4-12 weeks." },' .
		'    { name: "Renovation Consulting", from: "£180/day", summary: "Independent oversight through a build: quote review, site visits, second opinions on site. Booked by the day." },' .
		'    { name: "Room Refresh", from: "£650", summary: "A single afternoon on site plus a follow-up plan: layout, materials shortlist, up to five sourced pieces. No structural changes." }' .
		'  ];' .
		'  function waitForSdk(timeoutMs) {' .
		'    var started = Date.now();' .
		'    return new Promise(function (resolve) {' .
		'      (function poll() {' .
		'        if (window.BusymateAI && typeof window.BusymateAI.registerPageTools === "function") { resolve(true); return; }' .
		'        if (Date.now() - started > (timeoutMs || 15000)) { resolve(false); return; }' .
		'        setTimeout(poll, 150);' .
		'      })();' .
		'    });' .
		'  }' .
		'  var TOOLS = [' .
		'    {' .
		'      name: "list_services",' .
		'      title: "List Larkspur Studio services",' .
		'      description: "The three service tiers this studio offers, with their starting price and a one-line summary — call this before quoting a price in prose.",' .
		'      inputSchema: { type: "object", properties: {}, additionalProperties: false },' .
		'      annotations: { readOnlyHint: true },' .
		'      execute: function () { return Promise.resolve({ services: SERVICES }); }' .
		'    },' .
		'    {' .
		'      name: "get_contact_info",' .
		'      title: "Get Larkspur Studio contact details",' .
		'      description: "This demo studio\'s (fictional) address, email and hours.",' .
		'      inputSchema: { type: "object", properties: {}, additionalProperties: false },' .
		'      annotations: { readOnlyHint: true },' .
		'      execute: function () {' .
		'        return Promise.resolve({ address: "14 Cotham Vale, Bristol BS6 (by appointment only)", email: "hello@wordpress.demo.busymate.ai", hours: "Monday-Friday, 9:00-17:30", note: "Demo business — this address/email is not real." });' .
		'      }' .
		'    },' .
		'    {' .
		'      name: "who_is_signed_in",' .
		'      title: "Who is signed in",' .
		'      description: "The visitor\'s name if they are signed in to this demo site, or a note that nobody is.",' .
		'      inputSchema: { type: "object", properties: {}, additionalProperties: false },' .
		'      annotations: { readOnlyHint: true },' .
		'      execute: function () {' .
		'        var name = document.documentElement.getAttribute("data-larkspur-customer") || "";' .
		'        return Promise.resolve(name ? { signedIn: true, name: name } : { signedIn: false, detail: "Nobody is signed in in this browser." });' .
		'      }' .
		'    },' .
		'    {' .
		'      name: "request_consultation",' .
		'      title: "Request a consultation",' .
		'      description: "Start a consultation request with Larkspur Studio. Call this as soon as the visitor says they want to book or get a quote, even before they have given every detail — ask for whatever is missing after.",' .
		'      inputSchema: { type: "object", properties: {' .
		'        name: { type: "string", description: "The visitor\'s name" },' .
		'        email: { type: "string", description: "Where to reach them" },' .
		'        project: { type: "string", description: "What they want done, in their own words" }' .
		'      }, additionalProperties: false },' .
		'      annotations: { readOnlyHint: false },' .
		'      execute: function (args) {' .
		'        return fetch(' . wp_json_encode( $consult_url ) . ', {' .
		'          method: "POST", credentials: "same-origin", cache: "no-store",' .
		'          headers: { "content-type": "application/json", "x-wp-nonce": ' . wp_json_encode( $nonce ) . ' },' .
		'          body: JSON.stringify(args || {})' .
		'        }).then(function (r) { return r.json(); }).then(function (d) {' .
		'          if (!d || !d.ok) return { error: d && d.detail ? d.detail : "could_not_submit" };' .
		'          return { confirmed: true, reference: d.reference };' .
		'        });' .
		'      }' .
		'    }' .
		'  ];' .
		'  waitForSdk().then(function (ok) {' .
		'    if (!ok) return;' .
		'    window.BusymateAI.registerPageTools(TOOLS).then(function () {' .
		'      window.__larkspurPageTools = { ok: true, registered: TOOLS.map(function (t) { return t.name; }) };' .
		'    }).catch(function (e) {' .
		'      window.__larkspurPageTools = { ok: false, reason: String(e && e.message ? e.message : e) };' .
		'    });' .
		'  });' .
		'}());';
}

/**
 * The REST route `request_consultation` posts to. Stores the lead as a
 * private custom post so it is reviewable the same way any other content on
 * this demo is (`wp post list --post_type=bmai_lead`), never emailed
 * anywhere and never exposed by any public route.
 *
 * @return void
 */
function bmai_register_consultation_cpt() {
	register_post_type(
		'bmai_lead',
		array(
			'label'    => __( 'Consultation requests', 'busymate-ai' ),
			'public'   => false,
			'show_ui'  => false,
			'supports' => array( 'title', 'editor', 'custom-fields' ),
		)
	);
}
add_action( 'init', 'bmai_register_consultation_cpt' );

/**
 * @return void
 */
function bmai_register_consultation_route() {
	register_rest_route(
		'busymate/v1',
		'/consultation',
		array(
			'methods'             => 'POST',
			'permission_callback' => '__return_true',
			'callback'            => 'bmai_handle_consultation_request',
		)
	);
}
add_action( 'rest_api_init', 'bmai_register_consultation_route' );

/**
 * @param WP_REST_Request $request The mint request.
 * @return WP_REST_Response
 */
function bmai_handle_consultation_request( $request ) {
	$name    = sanitize_text_field( (string) $request->get_param( 'name' ) );
	$email   = sanitize_email( (string) $request->get_param( 'email' ) );
	$project = sanitize_textarea_field( (string) $request->get_param( 'project' ) );

	if ( '' === $name && '' === $email && '' === $project ) {
		return new WP_REST_Response( array( 'ok' => false, 'detail' => 'Tell me your name and what you\'re planning and I\'ll start the request.' ), 200 );
	}

	$user     = is_user_logged_in() ? wp_get_current_user() : null;
	$post_id  = wp_insert_post(
		array(
			'post_type'    => 'bmai_lead',
			'post_status'  => 'private',
			'post_title'   => $name ? $name : ( $user ? $user->display_name : 'Anonymous visitor' ),
			'post_content' => $project,
			'post_author'  => 1,
		)
	);
	if ( is_wp_error( $post_id ) || ! $post_id ) {
		return new WP_REST_Response( array( 'ok' => false, 'detail' => 'Could not save the request — please try again.' ), 200 );
	}
	update_post_meta( $post_id, 'email', $email );
	if ( $user ) {
		update_post_meta( $post_id, 'wp_user_id', $user->ID );
	}
	return new WP_REST_Response(
		array(
			'ok'        => true,
			'reference' => 'LS-' . $post_id,
		),
		200
	);
}
