#!/usr/bin/env node
// sites/discord/build.mjs — regenerate public/assets/page-tools.data.js from
// backend/tool-schema.mjs + page-tools.config.mjs, so the page-tool data twin
// (and through it /webmcp-catalog.json) can never drift from the MCP server's
// tool table. Run by scripts/build-demo.sh discord.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { toolsFor } from "./backend/tool-schema.mjs";
import { PAGE_TOOLS, WEBMCP_ONLY } from "./page-tools.config.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const T = toolsFor("Pixelforge Games");

const specs = [
  ...PAGE_TOOLS.map((name) => ({
    name,
    description: T[name].description,
    inputSchema: T[name].inputSchema,
    annotations: { readOnlyHint: !!T[name].readOnlyHint },
  })),
  ...Object.entries(WEBMCP_ONLY).map(([name, t]) => ({
    name,
    description: t.description,
    inputSchema: t.inputSchema,
    annotations: { readOnlyHint: !!t.readOnlyHint },
  })),
];

fs.writeFileSync(
  path.join(here, "public", "assets", "page-tools.data.js"),
  `// sites/discord/public/assets/page-tools.data.js
//
// GENERATED by sites/discord/build.mjs — do not edit by hand.
//
// The SAME tool specs the page registers via document.modelContext (see the
// module script at the bottom of index.html), kept here as plain data so
// scripts/gen-webmcp-catalog.mjs can publish an honest /webmcp-catalog.json
// for a reader that never executes JavaScript. Both come from
// backend/tool-schema.mjs + page-tools.config.mjs, so the page, the catalogue
// and the MCP server cannot disagree.
export const TOOL_SPECS = ${JSON.stringify(specs, null, 2)};
`,
);
console.log(`discord: page-tools.data.js — ${specs.length} page tools`);
