<?php
/**
 * Plugin Name: Fernweh — agent-readable surface
 * Description: Serves this demo store's six agent-readable layers (llms.txt, llms-full.txt,
 *              agents.json + its .well-known twin, webmcp-catalog.json, robots.txt, sitemap.xml),
 *              the Markdown twin of every policy page, and the page-tool bundle — all from
 *              WordPress itself.
 * Version:     1.1.0
 * Author:      Busymate AI demo playground
 *
 * WHY THIS IS A PLUGIN AND NOT A DOCROOT.
 * Every other demo on the playground is a static docroot that `scripts/deploy.sh`
 * rsyncs, and its six agent files are ordinary files nginx serves. This demo is a
 * real WordPress application in its own container: deploy.sh filters on
 * `type == "static"` and deliberately never touches it, and nginx proxies every
 * path to WordPress. So the files have to come OUT of WordPress, and dropping
 * them into the WordPress docroot is not an option either — an `index.html`
 * there would shadow `index.php` and take the shop down.
 *
 * The generated bytes therefore ship in `data/` next to this file (synced verbatim from
 * `sites/woo/public/` by sites/woo/provision.sh, which is how they stay
 * infrastructure-as-code) and this plugin answers the paths for them, on `init`
 * at priority 1 — before WordPress can canonicalise a path it does not
 * recognise into a trailing-slash redirect to an HTML page.
 *
 * `sitemap.xml` is NOT a shipped file: it is built here from the pages and
 * products that are actually published, with their real modified dates, because
 * an honest sitemap is the one the site can prove.
 *
 * @package Fernweh_Demo
 */

defined( 'ABSPATH' ) || exit;

define( 'FERNWEH_DATA_DIR', __DIR__ . '/data' );
define( 'FERNWEH_ORIGIN', 'https://woo.demo.busymate.ai' );

/**
 * The static path table: request path => [ file under data/, content type ].
 *
 * @return array<string, array{0:string,1:string}>
 */
function fernweh_static_routes() {
	return array(
		'/llms.txt'                 => array( 'llms.txt', 'text/plain; charset=utf-8' ),
		'/llms.txt.md'              => array( 'llms.txt.md', 'text/markdown; charset=utf-8' ),
		'/llms-full.txt'            => array( 'llms-full.txt', 'text/plain; charset=utf-8' ),
		'/agents.json'              => array( 'agents.json', 'application/json; charset=utf-8' ),
		'/.well-known/agents.json'  => array( '.well-known/agents.json', 'application/json; charset=utf-8' ),
		'/AGENTS.md'                => array( 'AGENTS.md', 'text/markdown; charset=utf-8' ),
		'/sitemap.md'               => array( 'sitemap.md', 'text/markdown; charset=utf-8' ),
		'/glossary'                 => array( 'glossary.html', 'text/html; charset=utf-8' ),
		'/glossary.md'              => array( 'glossary.md', 'text/markdown; charset=utf-8' ),
		'/openapi.json'             => array( 'openapi.json', 'application/json; charset=utf-8' ),
		'/.well-known/mcp.json'     => array( '.well-known/mcp.json', 'application/json; charset=utf-8' ),
		'/agent-permissions.json'  => array( 'agent-permissions.json', 'application/json; charset=utf-8' ),
		'/.well-known/agent-permissions.json' => array( '.well-known/agent-permissions.json', 'application/json; charset=utf-8' ),
		// RFC 9727 §4: a linkset response is application/linkset+json, not plain JSON.
		'/.well-known/api-catalog'  => array( '.well-known/api-catalog', 'application/linkset+json; charset=utf-8' ),
		'/webmcp-catalog.json'      => array( 'webmcp-catalog.json', 'application/json; charset=utf-8' ),
		'/index.md'                 => array( 'index.md', 'text/markdown; charset=utf-8' ),
		'/shipping.md'              => array( 'shipping.md', 'text/markdown; charset=utf-8' ),
		'/returns.md'               => array( 'returns.md', 'text/markdown; charset=utf-8' ),
		'/privacy.md'               => array( 'privacy.md', 'text/markdown; charset=utf-8' ),
		'/terms.md'                 => array( 'terms.md', 'text/markdown; charset=utf-8' ),
		'/assets/page-tools.js'     => array( 'assets/page-tools.js', 'text/javascript; charset=utf-8' ),
		'/assets/page-tools.data.js' => array( 'assets/page-tools.data.js', 'text/javascript; charset=utf-8' ),
		// The shop's own mark, in the sizes the assistant and a link preview ask
		// for. Built by sites/_shared/brand/build-brand.mjs from brand/mark.svg —
		// the widget's avatar is this file, so a 404 here is a generic-looking
		// assistant on a branded store.
		'/img/mark.png'             => array( 'img/mark.png', 'image/png' ),
		// Every product photograph's author + licence (owner rule: real, credited imagery).
		'/img/CREDITS.md'           => array( 'img/CREDITS.md', 'text/markdown; charset=utf-8' ),
		'/img/logo.svg'             => array( 'img/logo.svg', 'image/svg+xml' ),
		'/img/og.png'               => array( 'img/og.png', 'image/png' ),
		'/apple-touch-icon.png'     => array( 'apple-touch-icon.png', 'image/png' ),
		'/favicon.svg'              => array( 'favicon.svg', 'image/svg+xml' ),
	);
}

/**
 * The requested path, without the query string.
 *
 * @return string
 */
function fernweh_request_path() {
	$uri = isset( $_SERVER['REQUEST_URI'] ) ? wp_unslash( $_SERVER['REQUEST_URI'] ) : '';
	if ( ! is_string( $uri ) || '' === $uri ) {
		return '';
	}
	$path = wp_parse_url( $uri, PHP_URL_PATH );
	return is_string( $path ) ? $path : '';
}

/**
 * Answer the agent-readable paths before WordPress routes anything.
 *
 * @return void
 */
function fernweh_serve_agent_files() {
	if ( is_admin() ) {
		return;
	}
	$path   = fernweh_request_path();
	$routes = fernweh_static_routes();

	if ( '/robots.txt' === $path ) {
		fernweh_send( fernweh_robots(), 'text/plain; charset=utf-8', 'public, max-age=600' );
	}
	if ( '/sitemap.xml' === $path ) {
		fernweh_send( fernweh_sitemap(), 'application/xml; charset=utf-8', 'public, max-age=600' );
	}
	if ( ! isset( $routes[ $path ] ) ) {
		return;
	}
	list( $file, $type ) = $routes[ $path ];
	$full                = FERNWEH_DATA_DIR . '/' . $file;
	if ( ! is_readable( $full ) ) {
		status_header( 404 );
		header( 'Content-Type: application/json; charset=utf-8' );
		header( 'Cache-Control: no-store' );
		echo wp_json_encode( array( 'error' => 'agent_file_missing', 'path' => $path ) );
		exit;
	}
	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- a local generated file, not a remote fetch.
	fernweh_send( file_get_contents( $full ), $type, 'public, max-age=300, stale-while-revalidate=3600' );
}
add_action( 'init', 'fernweh_serve_agent_files', 1 );

/**
 * Emit one body and stop.
 *
 * @param string $body    The response body.
 * @param string $type    Content type.
 * @param string $cache   Cache-Control value.
 * @return void
 */
function fernweh_send( $body, $type, $cache ) {
	status_header( 200 );
	header( 'Content-Type: ' . $type );
	header( 'Cache-Control: ' . $cache );
	header( 'Access-Control-Allow-Origin: *' );
	header( 'X-Content-Type-Options: nosniff' );
	echo $body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- pre-rendered generated content.
	exit;
}

/**
 * robots.txt — every AI crawler named explicitly, and a Sitemap line that
 * points at a sitemap this site actually serves. WordPress's own virtual
 * robots.txt names none of them and pointed at /wp-sitemap.xml, which 404s here.
 *
 * @return string
 */
function fernweh_robots() {
	$agents = array( 'GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-User', 'anthropic-ai', 'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'Applebot-Extended', 'CCBot', 'Bytespider', 'meta-externalagent' );
	$out    = "# Fernweh Supply Co. — a Busymate AI demonstration store.\n"
		. "# Everything here is readable by an agent on purpose: see /llms.txt and /agents.json.\n\n"
		. "User-agent: *\n"
		. "Allow: /\n"
		. "Disallow: /cart/\n"
		. "Disallow: /checkout/\n"
		. "Disallow: /my-account/\n"
		. "Disallow: /*?add-to-cart=\n\n";
	foreach ( $agents as $agent ) {
		$out .= 'User-agent: ' . $agent . "\nAllow: /\n\n";
	}
	$out .= 'Sitemap: ' . FERNWEH_ORIGIN . "/sitemap.xml\n";
	return $out;
}

/**
 * An honest sitemap: the pages and products that are really published, each
 * with the date WordPress last modified it.
 *
 * @return string
 */
function fernweh_sitemap() {
	$urls = array( array( 'loc' => FERNWEH_ORIGIN . '/', 'mod' => '', 'pri' => '1.0' ) );

	$pages = get_posts(
		array(
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'posts_per_page' => 50,
			'orderby'        => 'menu_order',
			'order'          => 'ASC',
		)
	);
	foreach ( $pages as $page ) {
		$link = get_permalink( $page );
		// The cart, checkout and account pages are a shopper's private workspace,
		// not content: robots.txt disallows them, so listing them would be a
		// sitemap contradicting the file next to it.
		if ( preg_match( '#/(cart|checkout|my-account)/#', (string) $link ) ) {
			continue;
		}
		$urls[] = array( 'loc' => $link, 'mod' => get_post_modified_time( 'c', true, $page ), 'pri' => '0.6' );
	}

	if ( function_exists( 'wc_get_products' ) ) {
		$products = wc_get_products( array( 'status' => 'publish', 'limit' => 200 ) );
		foreach ( $products as $product ) {
			$urls[] = array(
				'loc' => $product->get_permalink(),
				'mod' => $product->get_date_modified() ? $product->get_date_modified()->date( 'c' ) : '',
				'pri' => '0.8',
			);
		}
	}

	foreach ( get_terms( array( 'taxonomy' => 'product_cat', 'hide_empty' => true ) ) as $term ) {
		if ( is_wp_error( $term ) ) {
			continue;
		}
		$urls[] = array( 'loc' => get_term_link( $term ), 'mod' => '', 'pri' => '0.5' );
	}

	// The agent-readable layers are pages too, for a reader that arrives here first.
	foreach ( array( '/llms.txt', '/llms-full.txt', '/agents.json', '/webmcp-catalog.json' ) as $extra ) {
		$urls[] = array( 'loc' => FERNWEH_ORIGIN . $extra, 'mod' => '', 'pri' => '0.4' );
	}

	$xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n";
	foreach ( $urls as $url ) {
		if ( empty( $url['loc'] ) || is_wp_error( $url['loc'] ) ) {
			continue;
		}
		$xml .= "  <url>\n    <loc>" . esc_url( $url['loc'] ) . "</loc>\n";
		if ( $url['mod'] ) {
			$xml .= '    <lastmod>' . esc_html( $url['mod'] ) . "</lastmod>\n";
		}
		$xml .= '    <priority>' . esc_html( $url['pri'] ) . "</priority>\n  </url>\n";
	}
	return $xml . "</urlset>\n";
}

/**
 * The links that let a reader which never runs the page find all of the above.
 *
 * @return void
 */
function fernweh_head_links() {
	$twins = array(
		'shipping' => '/shipping.md',
		'returns'  => '/returns.md',
		'privacy'  => '/privacy.md',
		'terms'    => '/terms.md',
	);
	echo "\n<!-- This store is agent-readable on purpose. -->\n";
	echo '<link rel="webmcp-catalog" href="/webmcp-catalog.json">' . "\n";
	// #2905/C6 (corrected 2026-09-14 against a live agent-ready.dev rescan):
	// the bespoke discovery card lives at the WELL-KNOWN path — the bare
	// /agents.json path is what the real external checker reads as the
	// agentsJson v0.1.0 tool-actions manifest.
	echo '<link rel="alternate" type="application/json" href="/.well-known/agents.json" title="Agent card">' . "\n";
	echo '<link rel="describedby" href="/llms.txt">' . "\n";
	echo '<link rel="alternate" type="text/plain" href="/llms.txt" title="llms.txt">' . "\n";
	echo '<link rel="alternate" type="text/plain" href="/llms-full.txt" title="llms-full.txt">' . "\n";
	$path = untrailingslashit( fernweh_request_path() );
	foreach ( $twins as $slug => $md ) {
		if ( '/' . $slug === $path ) {
			echo '<link rel="alternate" type="text/markdown" href="' . esc_attr( $md ) . '" title="This page as Markdown">' . "\n";
		}
	}
	if ( is_front_page() || is_shop() ) {
		echo '<link rel="alternate" type="text/markdown" href="/index.md" title="This page as Markdown">' . "\n";
	}
}
add_action( 'wp_head', 'fernweh_head_links', 2 );

/**
 * The shop's own icon, in place of WordPress's default grey W.
 *
 * A reader that only looks at the favicon (the AI-readiness scan's persona
 * step is one) reported this store's brand as "Woo" with the WordPress logo,
 * which is the platform showing through a shop that has its own mark.
 *
 * @return void
 */
function fernweh_icon_links() {
	echo '<link rel="icon" href="/favicon.svg" type="image/svg+xml">' . "\n";
	echo '<link rel="apple-touch-icon" href="/apple-touch-icon.png">' . "\n";
	echo '<meta name="theme-color" content="#1e4046">' . "\n";
}
add_action( 'wp_head', 'fernweh_icon_links', 1 );

/**
 * Open Graph and Twitter cards. The theme prints none, so a link to this store
 * shared anywhere — and every reader that takes og:* as the page's summary —
 * saw nothing at all. Built from what the page really is: a product's own name,
 * price and image on a product page, the shop's on everything else.
 *
 * @return void
 */
function fernweh_open_graph() {
	$title = wp_get_document_title();
	$url   = home_url( add_query_arg( array() ) );
	$image = FERNWEH_ORIGIN . '/img/og.png';
	$type  = 'website';
	$desc  = 'Fernweh Supply Co. — small-batch packs, merino layers, bottles and notebooks, made in Leipzig. '
		. 'A Busymate AI demonstration store: nothing is dispatched and no payment is taken.';

	// The shop IS a WordPress page, and it is the front page, so this arm has to
	// come first: `is_page()` is true here and `get_the_excerpt()` inside a
	// product loop returns the FIRST PRODUCT's summary, which described the whole
	// store as a merino crew.
	if ( is_front_page() || ( function_exists( 'is_shop' ) && is_shop() ) ) {
		$type  = 'website';
		$title = 'Fernweh Supply Co. — small-batch gear for the long way round';
	} elseif ( function_exists( 'is_product' ) && is_product() ) {
		$product = function_exists( 'wc_get_product' ) ? wc_get_product( get_the_ID() ) : null;
		if ( $product ) {
			$type  = 'product';
			$title = wp_strip_all_tags( $product->get_name() );
			$short = wp_strip_all_tags( $product->get_short_description() );
			$desc  = $short ? $short : $desc;
			$src   = wp_get_attachment_image_url( $product->get_image_id(), 'large' );
			if ( $src ) {
				$image = $src;
			}
		}
	} elseif ( is_page() ) {
		$type    = 'article';
		$excerpt = wp_strip_all_tags( get_the_excerpt() );
		if ( $excerpt ) {
			$desc = $excerpt;
		}
	}

	$tags = array(
		'og:type'             => $type,
		'og:site_name'        => 'Fernweh Supply Co.',
		'og:title'            => $title,
		'og:description'      => $desc,
		'og:url'              => $url,
		'og:image'            => $image,
		'og:locale'           => 'en_US',
		'twitter:card'        => 'summary_large_image',
		'twitter:title'       => $title,
		'twitter:description' => $desc,
		'twitter:image'       => $image,
	);
	foreach ( $tags as $name => $value ) {
		if ( ! $value ) {
			continue;
		}
		$attr = 0 === strpos( $name, 'og:' ) ? 'property' : 'name';
		printf(
			'<meta %1$s="%2$s" content="%3$s">' . "\n",
			esc_attr( $attr ),
			esc_attr( $name ),
			esc_attr( wp_html_excerpt( $value, 300, '…' ) )
		);
	}
}
add_action( 'wp_head', 'fernweh_open_graph', 3 );
