#!/usr/bin/env bash
# Stand the WooCommerce demo up on the demos droplet: swap, containers, vhost, TLS.
# IDEMPOTENT — safe to re-run; it never touches an existing container or cert.
# Run as root ON THE BOX:
#
#   REPO_DIR=/srv/demos/_repo bash /srv/demos/_repo/sites/woo/provision.sh
#
# Then seed the shop:  ROOT=/srv/demos/woo bash /srv/demos/_repo/sites/woo/seed/seed.sh
#
# This demo is `type: "dynamic"`, so scripts/deploy.sh skips it entirely (it only
# handles static docroots). That is deliberate: a deploy run must never rsync over
# a live WordPress install or re-render this vhost from the static template.
set -euo pipefail

NAME=woo
PORT=8106
MCP_PORT=8107
FQDN=woo.demo.busymate.ai
ROOT=/srv/demos/$NAME
DATA=$ROOT/data
ACME=$ROOT/acme
NET=demo-woo-net
REPO_DIR="${REPO_DIR:-/srv/demos/_repo}"
TPL="$REPO_DIR/infra/nginx"
CERT_EMAIL="${CERT_EMAIL:-admin@busymate.ai}"
CONF=/etc/nginx/sites-available/$FQDN.conf

# --- 1. swap --------------------------------------------------------------
# The droplet is 2 GB with no swap and ~1.4 GB free. MariaDB + PHP-FPM under
# Apache will fit, but a plugin install or an image import can spike past it,
# and the OOM killer takes the database first.
if ! swapon --show | grep -q swapfile; then
  fallocate -l 1G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >>/etc/fstab
  sysctl -qw vm.swappiness=10
  grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' >>/etc/sysctl.conf
fi

# --- 2. layout + secrets (generated HERE, never in argv, never in the repo) --
mkdir -p "$DATA/db" "$DATA/wp" "$ACME"
chmod 755 "$ROOT" "$ACME"
if [ ! -f "$DATA/.env" ]; then
  umask 077
  {
    echo "WOO_DB_NAME=wordpress"
    echo "WOO_DB_USER=wordpress"
    echo "WOO_DB_PASS=$(openssl rand -hex 24)"
    echo "WOO_DB_ROOT_PASS=$(openssl rand -hex 24)"
    echo "WOO_ADMIN_USER=fernweh_ops"
    echo "WOO_ADMIN_PASS=$(openssl rand -base64 21 | tr -d '/+=')Aa1!"
    echo "WOO_ADMIN_EMAIL=ops@woo.demo.busymate.ai"
    # The demo shopper is a PROVIDED account: its password is meant to be known
    # and stable, so it is fixed here rather than generated. It grants nothing
    # but this throwaway store's own order history. Everything above it — the
    # database passwords and the WordPress admin — is generated per box and
    # never leaves it.
    echo "WOO_CUSTOMER_EMAIL=demo@woo.demo.busymate.ai"
    echo "WOO_CUSTOMER_USER=demo"
    echo "WOO_CUSTOMER_PASS=FernwehDemo2026!"
  } >"$DATA/.env"
  chmod 600 "$DATA/.env"
fi
set -a; . "$DATA/.env"; set +a

# --- 3. containers --------------------------------------------------------
docker network inspect "$NET" >/dev/null 2>&1 || docker network create "$NET" >/dev/null

if ! docker inspect demo-woo-db >/dev/null 2>&1; then
  docker run -d --name demo-woo-db --restart unless-stopped \
    --network "$NET" \
    -e MARIADB_DATABASE="$WOO_DB_NAME" \
    -e MARIADB_USER="$WOO_DB_USER" \
    -e MARIADB_PASSWORD="$WOO_DB_PASS" \
    -e MARIADB_ROOT_PASSWORD="$WOO_DB_ROOT_PASS" \
    -v "$DATA/db:/var/lib/mysql" \
    --memory 512m \
    mariadb:11 \
    --innodb-buffer-pool-size=64M --performance-schema=OFF \
    --max-connections=40 --key-buffer-size=8M >/dev/null
fi

# WP_HOME/WP_SITEURL are pinned to the public https origin and the forwarded
# scheme is trusted, so WordPress builds https URLs behind the edge proxy
# instead of redirect-looping or emitting http assets on an https page.
read -r -d '' WP_EXTRA <<'PHP' || true
/* Behind the demo edge proxy: trust the forwarded scheme so WP builds https URLs. */
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
    $_SERVER['HTTPS'] = 'on';
}
if ( isset( $_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}
define( 'WP_HOME',    'https://woo.demo.busymate.ai' );
define( 'WP_SITEURL', 'https://woo.demo.busymate.ai' );
define( 'FORCE_SSL_ADMIN', true );
define( 'DISALLOW_FILE_EDIT', true );
define( 'AUTOMATIC_UPDATER_DISABLED', true );
define( 'WP_MEMORY_LIMIT', '256M' );
PHP

if ! docker inspect demo-woo >/dev/null 2>&1; then
  docker run -d --name demo-woo --restart unless-stopped \
    --network "$NET" \
    -p "127.0.0.1:${PORT}:80" \
    -e WORDPRESS_DB_HOST=demo-woo-db:3306 \
    -e WORDPRESS_DB_NAME="$WOO_DB_NAME" \
    -e WORDPRESS_DB_USER="$WOO_DB_USER" \
    -e WORDPRESS_DB_PASSWORD="$WOO_DB_PASS" \
    -e WORDPRESS_TABLE_PREFIX=wp_ \
    -e WORDPRESS_CONFIG_EXTRA="$WP_EXTRA" \
    -v "$DATA/wp:/var/www/html" \
    --memory 768m \
    wordpress:php8.3-apache >/dev/null
fi

# --- 3b. what makes it a DEMO and not just a shop -------------------------
# Two mu-plugins and the generated bytes they serve. mu-plugins load before
# everything and cannot be deactivated from an admin screen nobody can reach,
# which is exactly right for the two things this store must never lose: its
# agent-readable layers and its demo experience.
#
# `public/` is the build output (node sites/woo/build.mjs) and is copied in
# VERBATIM as the plugin's data/ — that is how the six layers stay
# infrastructure-as-code on a demo scripts/deploy.sh never touches.
MU="$DATA/wp/wp-content/mu-plugins"
mkdir -p "$MU"
cp "$REPO_DIR/sites/$NAME/wp/mu-plugins/"*.php "$MU/"
rm -rf "$MU/data"
mkdir -p "$MU/data"
cp -R "$REPO_DIR/sites/$NAME/public/." "$MU/data/"
chown -R www-data:www-data "$MU"
find "$MU" -type d -exec chmod 755 {} + ; find "$MU" -type f -exec chmod 644 {} +

# --- 3c. the demo's own MCP server ----------------------------------------
# A separate container on $MCP_PORT serving exactly one path, /mcp. It reads the
# shop over its PUBLIC Store API for the catalogue and over the keyed REST API
# for the order book; the key pair is injected here from the 0600 file on the
# box and is in no image, no argv that outlives this shell, and no repo.
jqd() { python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get(sys.argv[2],""))' "$REPO_DIR/sites/$NAME/demo.json" "$1"; }
TENANT_ID="$(jqd tenant_id)"
CONNECTOR_ID="$(jqd connector_id)"

# The tenant-set HS256 verifier the platform signs its customer actor tokens
# with (`set_connector_actor_verifier`). Generated on the box, 0600, never in
# the repo; the SAME value is installed on the connector through the platform.
# Everything else in the file is public and is refreshed from demo.json on every
# run, so the connector id cannot drift from the one this repo records.
if [ ! -f "$DATA/.actor-verifier" ]; then
  umask 077
  echo "BMAI_SUPPORT_ACTOR_SECRET=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')" >"$DATA/.actor-verifier.secret"
  chmod 600 "$DATA/.actor-verifier.secret"
fi
{
  cat "$DATA/.actor-verifier.secret"
  echo "BMAI_SUPPORT_TENANT_ID=$TENANT_ID"
  echo "BMAI_SUPPORT_CONNECTOR_ID=$CONNECTOR_ID"
  echo "BMAI_SUPPORT_AUDIENCE=https://$FQDN"
} >"$DATA/.actor-verifier"
chmod 600 "$DATA/.actor-verifier"

if [ -f "$DATA/.wc-api-key" ]; then
  docker build -q -f "$REPO_DIR/sites/$NAME/backend/Dockerfile" -t demo-woo-backend "$REPO_DIR" >/dev/null
  docker rm -f demo-woo-backend >/dev/null 2>&1 || true
  docker run -d --name demo-woo-backend --restart unless-stopped \
    --network "$NET" \
    -p "127.0.0.1:${MCP_PORT}:${MCP_PORT}" \
    -e PORT="$MCP_PORT" \
    -e WOO_ORIGIN="https://$FQDN" \
    -e WOO_UPSTREAM="http://demo-woo" \
    -e TENANT_ID="$TENANT_ID" \
    --env-file "$DATA/.wc-api-key" \
    --env-file "$DATA/.actor-verifier" \
    --memory 192m \
    demo-woo-backend >/dev/null
  [ -n "$CONNECTOR_ID" ] || echo "NOTE: demo.json has no connector_id yet — the three delegated tools stay hidden until it does."
else
  echo "WARN: $DATA/.wc-api-key is absent — run seed/seed.sh first; the MCP server is NOT started."
fi

# --- 4. vhost + TLS -------------------------------------------------------
render() { # <template>
  sed -e "s#__FQDN__#${FQDN}#g" -e "s#__PORT__#${PORT}#g" -e "s#__MCP_PORT__#${MCP_PORT}#g" -e "s#__ACME_ROOT__#${ACME}#g" "$1" >"$CONF"
  ln -sf "$CONF" "/etc/nginx/sites-enabled/${FQDN}.conf"
  nginx -t && systemctl reload nginx
}
mkdir -p "$ACME/.well-known/acme-challenge"
chmod -R 755 "$ACME"
if [ ! -f "/etc/letsencrypt/live/${FQDN}/fullchain.pem" ]; then
  render "$TPL/wordpress-http.conf.template"
  certbot certonly --webroot -w "$ACME" --non-interactive --agree-tos -m "$CERT_EMAIL" -d "$FQDN"
fi
render "$TPL/wordpress-https.conf.template"

docker ps --filter name=demo-woo --format '{{.Names}}  {{.Status}}  {{.Ports}}'
echo "vhost   $CONF"
curl -sS -o /dev/null -w 'https://%{url.host}/healthz -> %{http_code}\n' "https://$FQDN/healthz" 2>/dev/null \
  || curl -sS -o /dev/null -w "healthz -> %{http_code}\n" "https://$FQDN/healthz"
