// sites/shopify/build.mjs — project backend/catalog.mjs (the ONE source of
// store truth) onto everything else the demo serves or publishes:
//   public/assets/catalog.js   the storefront's data (window.NORTHLINE)
//   public/catalog.json        the same catalog, machine-readable
//   public/index.html          the JSON-LD block between <!-- ld:start --> / <!-- ld:end -->
//   knowledge.json             the tenant knowledge_sources the assistant is grounded in
//   .publish/                  the exact MCP payloads (branding via the shared
//                              sites/_shared/brand/tenant-branding.mjs + the ONE publish)
// Run via scripts/build-demo.sh shopify; commit what changes.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { STORE, CATEGORIES, PRODUCTS, ORDERS, DEMO_CUSTOMER, POLICIES, FAQ, REVIEWS, TEAM, STORY, publicProduct, stockSummary } from "./backend/catalog.mjs";
import { execFileSync } from "node:child_process";

const here = path.dirname(fileURLToPath(import.meta.url));
const pub = path.join(here, "public");
const demo = JSON.parse(fs.readFileSync(path.join(here, "demo.json"), "utf8"));

// 1) storefront data
const site = { store: STORE, categories: CATEGORIES, products: PRODUCTS, reviews: REVIEWS, team: TEAM, story: STORY, faq: FAQ, policies: POLICIES, demoCustomer: DEMO_CUSTOMER, orders: ORDERS.map((o) => ({ orderNumber: o.orderNumber, status: o.status, placedAt: o.placedAt })) };
fs.mkdirSync(path.join(pub, "assets"), { recursive: true });
fs.writeFileSync(path.join(pub, "assets", "catalog.js"), `// generated by sites/shopify/build.mjs from backend/catalog.mjs — do not edit\nwindow.NORTHLINE = ${JSON.stringify(site)};\n`);
fs.writeFileSync(path.join(pub, "catalog.json"), JSON.stringify({ store: STORE, categories: CATEGORIES, products: PRODUCTS.map(publicProduct) }, null, 2) + "\n");

// 2) JSON-LD
const availability = (p) => {
  const s = Object.values(p.stock);
  if (s.every((x) => x === "sold_out")) return "https://schema.org/OutOfStock";
  if (s.some((x) => x === "in_stock" || x === "low")) return "https://schema.org/InStock";
  return "https://schema.org/BackOrder";
};
const ld = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "Store", name: STORE.name, url: STORE.url + "/", description: `${STORE.name} — outdoor gear with a lifetime warranty. A sample Shopify storefront demonstrating the Busymate AI app.`, additionalType: "https://schema.org/OnlineStore", logo: `${STORE.url}/img/mark.png`, telephone: STORE.phone, email: STORE.email, foundingDate: String(STORE.founded), address: { "@type": "PostalAddress", addressLocality: "Bellingham", addressRegion: "WA", addressCountry: "US" } },
    { "@type": "ItemList", itemListElement: PRODUCTS.map((p, i) => ({ "@type": "Product", position: i + 1, name: p.title, sku: p.sku, description: p.short, image: `${STORE.url}/img/products/${p.image}-960.webp`, url: `${STORE.url}/#p-${p.sku}`, brand: { "@type": "Brand", name: STORE.name }, offers: { "@type": "Offer", price: String(p.price), priceCurrency: STORE.currency, availability: availability(p), url: `${STORE.url}/#p-${p.sku}` } })) },
    { "@type": "FAQPage", mainEntity: [
      { "@type": "Question", name: `Is ${STORE.name} a real store?`, acceptedAnswer: { "@type": "Answer", text: "No. It is a sample Shopify storefront that demonstrates the Busymate AI app — no real orders, payments or accounts exist." } },
      ...FAQ.map((f) => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } })),
    ] },
  ],
};
const indexPath = path.join(pub, "index.html");
let html = fs.readFileSync(indexPath, "utf8");
const ldBlock = `<!-- ld:start -->\n<script type="application/ld+json">\n${JSON.stringify(ld, null, 1)}\n</script>\n<!-- ld:end -->`;
if (!/<!-- ld:start -->[\s\S]*<!-- ld:end -->/.test(html)) throw new Error("index.html lacks the <!-- ld:start --> … <!-- ld:end --> markers");
html = html.replace(/<!-- ld:start -->[\s\S]*<!-- ld:end -->/, ldBlock);
fs.writeFileSync(indexPath, html);

// 3) tenant knowledge (each source ≤ 20,000 chars, total ≤ 40,000)
const money = (n) => `$${n}`;
const productLines = PRODUCTS.map((p, i) => {
  const opts = [];
  if (p.options.colors) opts.push(`Colors: ${p.options.colors.join(", ")}`);
  if (p.options.sizes) opts.push(`Sizes: ${p.options.sizes.join(", ")}`);
  const price = p.compareAt ? `${money(p.price)} (was ${money(p.compareAt)})` : money(p.price);
  return `${i + 1}. ${p.title} (SKU ${p.sku}, ${CATEGORIES.find((c) => c.slug === p.category).name}) — ${price}. ${p.short} ${p.description} ${opts.join(". ")}${opts.length ? ". " : ""}Weight ${p.weight}. Specs: ${p.specs.join("; ")}. Stock: ${stockSummary(p)}`;
}).join("\n");
const knowledge_sources = [
  {
    key: "shopify:about-demo", label: "About this demo", kind: "fact",
    content: `This assistant runs on ${STORE.name}, a SAMPLE Shopify storefront built to demonstrate the Busymate AI app for Shopify. No real payments or customer accounts exist here — the products, policies AND the two demo orders are fictional but LIVE demo data (served through this site's own connected MCP server, not just text in this knowledge base). In a real merchant's store, this same assistant (installed via the Busymate AI Shopify app from the Shopify App Store) answers from the merchant's ACTUAL product catalog (synced automatically from Shopify), looks up REAL order status and tracking through the Shopify Admin API once a shopper confirms their order number and email, and can hand off to a human teammate through the merchant's Busymate AI inbox when a question needs a person. Never say a lookup 'isn't possible here' before actually trying the tool; the connected tools genuinely work on this demo. Store facts: founded ${STORE.founded} in ${STORE.hometown}; ${STORE.tagline}; lifetime warranty on every product; contact ${STORE.email}, ${STORE.phone}, hours ${STORE.hours}.`,
  },
  {
    key: "shopify:catalog", label: `${STORE.name} — product catalog`, kind: "reference",
    content: `${STORE.name} product catalog (${PRODUCTS.length} products, all prices in ${STORE.currency}, tax calculated at checkout). Categories: ${CATEGORIES.map((c) => `${c.name} — ${c.blurb}`).join(" | ")}.\n${productLines}\nBundles: the Trailhead Rain Shell and the Alpine Base Layer are often bought together as the 'wet-weather layering set' (no extra discount currently). Sale items: ${PRODUCTS.filter((p) => p.compareAt).map((p) => `${p.title} ${money(p.price)} down from ${money(p.compareAt)}`).join("; ")}. New arrivals: ${PRODUCTS.filter((p) => p.badge === "new").map((p) => p.title).join(", ")}. Bestsellers: ${PRODUCTS.filter((p) => p.badge === "bestseller").map((p) => p.title).join(", ")}.`,
  },
  {
    key: "shopify:shipping-returns", label: "Shipping, returns & warranty", kind: "reference",
    content: `${STORE.name} shipping: ${POLICIES.shipping.join(" ")}\nReturns and warranty: ${POLICIES.returns.join(" ")}\nFAQ:\n${FAQ.map((f) => `Q: ${f.q} A: ${f.a}`).join("\n")}`,
  },
  {
    key: "shopify:order-status-and-handoff", label: "Order status & human hand-off (this demo's connected tools)", kind: "howto",
    content: `This demo DOES support a real, working order lookup — try it: ask 'where's my order #1042' or 'what's the status of order #1039' and just CALL the get_order_status tool with that order number and the demo customer's email (${DEMO_CUSTOMER.email}) right away — do not refuse or claim this is impossible, the tool is connected and will return a real result for these two demo orders. When the chat cannot yet see who is asking, calling the tool is what makes a sign-in card appear in the conversation on its own; signing in is one click, no password, and returns them to this same conversation as the demo customer. ${ORDERS.map((o) => `Order ${o.orderNumber} (placed ${o.placedAt}): ${o.items.map((i) => `${i.qty}x ${PRODUCTS.find((p) => p.sku === i.sku).title} (${i.variant})`).join(" + ")}, status ${o.status.toUpperCase()}, tracking ${o.tracking.split(" ")[0]}${o.eta ? `, estimated delivery ${o.eta}` : ""}${o.deliveredAt ? `, delivered ${o.deliveredAt}` : ""}.`).join(" ")} A signed-OUT visitor asking about an order gets ONE short line and the tool call — never a description of a control or where it is, and never a claim the feature doesn't exist. start_return also works the same way, for an item that is actually on the order. The page's own cart: add_to_cart (by SKU) and view_cart run right on the page and update the visible cart badge and drawer. On a REAL merchant's Shopify store running the Busymate AI app, the same tool authenticates the shopper (order number + the email/phone on the order) and reads live status and tracking straight from Shopify's Admin API. If the assistant cannot resolve something (a damaged item, a refund exception, a policy question outside the knowledge base), it hands the conversation to a human teammate in the merchant's Busymate AI inbox — a visitor can also just type "I'd like to talk to a person".`,
  },
];
knowledge_sources.push({
  key: "shopify:assistant-playbook", label: "How this assistant acts (tools first)", kind: "howto",
  content: `Playbook for the ${STORE.name} assistant — act with the connected tools, never describe them. (1) CART: this page exposes site tools (search_products, add_to_cart, view_cart). When a shopper asks to add something to their cart, CALL add_to_cart with the product's SKU (and the variant, e.g. 'Moss / M') right away, then confirm what the cart now holds from the tool's result — never tell them to click a button or do it by hand. 'What's in my cart?' → CALL view_cart. (2) ORDERS: when a shopper asks about an order, tracking or delivery, CALL get_order_status immediately, even before they give the order number — the call shows an order-lookup card in the chat where they type the number and email; do not ask for the details in prose. If the tool answers not_signed_in, say ONE short line ("You will need to be signed in for that — here you go") and stop; a sign-in card appears in the conversation on its own and NEVER describe a control or where it is (the demo customer is ${DEMO_CUSTOMER.name}). (3) RETURNS: when a shopper wants to return or exchange something, CALL start_return immediately — it shows a return card (order, item, reason); do not list the items and ask in prose. (4) HUMAN: when a shopper asks for a person, a human, a teammate or an operator, CALL the request-human tool at once (the header also has a Request a human button) — never answer with email/phone/hours instead of the hand-off, and never say you 'will pass this on' without calling it. (5) Quote real numbers (weights, ratings, delivery days); when a variant is backordered or sold out say so and offer the nearest in-stock alternative.`,
});
for (const s of knowledge_sources) if (s.content.length > 20000) throw new Error(`knowledge source ${s.key} exceeds 20,000 chars (${s.content.length})`);
const total = knowledge_sources.reduce((n, s) => n + s.content.length, 0);
if (total > 40000) throw new Error(`knowledge total ${total} exceeds 40,000 chars`);
const knowledgePath = path.join(here, "knowledge.json");
const prev = fs.existsSync(knowledgePath) ? JSON.parse(fs.readFileSync(knowledgePath, "utf8")) : {};
const knowledge = { tenant_id: demo.tenant_id, embed_origins: prev.embed_origins || [STORE.url], confirm: true, knowledge_sources };
fs.writeFileSync(knowledgePath, JSON.stringify(knowledge, null, 2) + "\n");


// 3b) llms-full.txt — the whole store in one request for a reader that never runs the page.
const md = [];
md.push(`# ${STORE.name}`, "", `Source: ${STORE.url}/`, "", `> ${STORE.tagline} An independent outdoor-gear store founded ${STORE.founded} in ${STORE.hometown}: field-tested tents, packs, shells, boots and camp kitchen gear with a lifetime warranty and a repair program behind it. This is a Busymate AI demonstration store — a working storefront you can shop, sign in to and put an assistant through its paces on. No order is fulfilled, no payment is taken, and the demo customer is not a real person.`, "");
md.push("## The catalog", "", "| SKU | Product | Category | Price | Variants | Weight | Stock |", "|---|---|---|---|---|---|---|");
for (const p of PRODUCTS) md.push(`| ${p.sku} | ${p.title} | ${CATEGORIES.find((c) => c.slug === p.category).name} | ${money(p.price)}${p.compareAt ? ` (was ${money(p.compareAt)})` : ""} | ${[p.options.colors && `Colors: ${p.options.colors.join(", ")}`, p.options.sizes && `Sizes: ${p.options.sizes.join(", ")}`].filter(Boolean).join("; ") || "—"} | ${p.weight} | ${stockSummary(p)} |`);
md.push("", "Live prices, variants and stock also come from the MCP server's `list_products`, `search_products` and `get_product` tools, and from `GET /catalog.json`.", "");
md.push("## Product details", "");
for (const p of PRODUCTS) md.push(`### ${p.title} (${p.sku})`, "", `${p.short} ${p.description}`, "", `Specs: ${p.specs.join("; ")}.`, "");
md.push("## Categories", "", ...CATEGORIES.map((c) => `- **${c.name}** — ${c.blurb}`), "");
md.push("## Shipping", "", ...POLICIES.shipping.map((l) => `- ${l}`), "", "## Returns and warranty", "", ...POLICIES.returns.map((l) => `- ${l}`), "");
md.push("## Questions we get most", "", ...FAQ.map((f) => `**${f.q}**\n${f.a}\n`));
md.push("## Our story", "", ...STORY.paragraphs, "", ...STORY.stats.map((s) => `- ${s.value} ${s.label}`), "");
md.push("## The crew", "", ...TEAM.map((m) => `- ${m.name}, ${m.role} — ${m.note}`), "");
md.push("## Contact", "", `- Email: ${STORE.email}`, `- Phone: ${STORE.phone}`, `- Hours: ${STORE.hours}`, `- Workshop: ${STORE.hometown}`, `- A human teammate takes over in the chat when the assistant cannot resolve something ("I'd like to talk to a person").`, "");
md.push("## The demo customer", "", `Sign in on the page as ${DEMO_CUSTOMER.name} (${DEMO_CUSTOMER.email}) — a throwaway public account — to look up orders ${ORDERS.map((o) => `${o.orderNumber} (${o.status})`).join(" and ")} and start a return.`, "");
md.push("## For agents", "", `- MCP endpoint: ${STORE.url}/mcp (JSON-RPC 2.0 over HTTPS, no auth for catalog reads; order tools need an identified visitor)`, `- WebMCP page tools: ${STORE.url}/webmcp-catalog.json`, `- Agent card: ${STORE.url}/agents.json`, `- Short index: ${STORE.url}/llms.txt`, "");
fs.writeFileSync(path.join(pub, "llms-full.txt"), md.join("\n") + "\n");

// 4) the exact MCP payloads. The ONE publish comes from the shared
//    sites/_shared/publish/build-publish.mjs (brand.json + demo.json + publish.json +
//    the FULL knowledge array) — publish REPLACES the runtime config, so the whole
//    thing (brand block, origins, identity provider, connector, knowledge) goes out
//    every time. 1-set_tenant_branding.json is the column-level twin
//    (sites/_shared/brand/tenant-branding.mjs) for the Console "Brand & experience" view.
const outDir = path.join(here, ".publish");
fs.mkdirSync(outDir, { recursive: true });
const shared = path.join(here, "..", "_shared");
fs.writeFileSync(path.join(outDir, "1-set_tenant_branding.json"), execFileSync("node", [path.join(shared, "brand", "tenant-branding.mjs"), "shopify"], { encoding: "utf8" }));
const knowledgeArrayPath = path.join(outDir, "knowledge-sources.json");
fs.writeFileSync(knowledgeArrayPath, JSON.stringify(knowledge_sources, null, 2) + "\n");
fs.writeFileSync(path.join(outDir, "2-publish_tenant_runtime.json"), execFileSync("node", [path.join(shared, "publish", "build-publish.mjs"), "shopify", knowledgeArrayPath], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }));
const payloads = { "1-set_tenant_branding": 1, "2-publish_tenant_runtime": 1 };
console.log(`shopify: ${PRODUCTS.length} products → catalog.js, catalog.json, JSON-LD, knowledge.json (${total} chars / ${knowledge_sources.length} sources), .publish/{${Object.keys(payloads).join(",")}}.json`);
